# -*- coding: utf-8 -*-
"""Copia de PIA codigo Contabilidad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WP6CfJmVSmeHCJr6LsiYqfpFUt7ET_Lz
"""

from os import sep
from prettytable import PrettyTable
import os
LimpiarPantalla = lambda: os.system('cls')
  # -------- PRODUCTOS --------
  # -------- PRODUCTO A --------
  # ---- Primer semestre A ----
def productosABC():
    global Total_Anual
    LimpiarPantalla()
    print("------------------------------------")
    print("------------- Productos ------------")
    print("--- 1er semestre del producto A ---")
    cant_A = int(input("Numero de unidades: "))
    precio_A = int(input("Precio: "))
    Importe_A = (cant_A * precio_A)
    print(f"Importe del producto A: {Importe_A}")
    print("------------------------------------")
    print("") #Espacio
  # ---- Primer semestre A ----

  # ---- Segundo semestre A ----
    print("------------------------------------")
    print("--- 2do semestre del producto A ---")
    cant_A2 = int(input("Numero de unidades: "))
    precio_A2 = int(input("Precio: "))
    Importe_A2 = (cant_A2 * precio_A2)
    print(f"Importe del producto A: {Importe_A2}")
    print("------------------------------------")
    print("")#Espacio
    # ---- Segundo semestre A ----

    # ---- Total A ----
    print("------------------------------------")
    print("    ---- Total del producto A ----  ")
    Total_A = (Importe_A + Importe_A2)
    print(f"Total del producto B: {Total_A}")
    print("------------------------------------")
    print("") #Espacio
    # ---- Total A ----
    # -------- PRODUCTO A --------

    # -------- PRODUCTO B --------
    # ---- Primer semestre B ----
    print("------------------------------------")
    print("--- 1er semestre del producto B ---")
    cant_B = int(input("Numero de unidades: "))
    precio_B = int(input("Precio: "))
    Importe_B = (cant_B * precio_B)
    print(f"Importe del producto B: {Importe_B}")
    print("------------------------------------")
    print("")#Espacio
    # ---- Primer semestre B ----

    # ---- Segundo semestre B ----
    print("------------------------------------")
    print("--- 2do semestre del producto B ---")
    cant_B = int(input("Numero de unidades: "))
    precio_B = int(input("Precio: "))
    Importe_B2 = (cant_B * precio_B)
    print(f"Importe del producto B: {Importe_B2}")
    print("------------------------------------")
    print("")#espacio
    # ---- Segundo semestre B ----

    # ---- Total B ----
    print("------------------------------------")
    print("    ---- Total del producto B ----  ")
    Total_B = (Importe_B + Importe_B2)
    print(f"Total del producto B: {Total_B}")
    print("------------------------------------")
    print("") #espacio
    # ---- Total B ----
    # -------- PRODUCTO B --------

    # -------- PRODUCTO C --------
    # ---- Primer semestre C ----
    print("------------------------------------")
    print(" --- 1er semestre del producto C ---")
    cant_C = int(input("Numero de unidades: "))
    precio_C = int(input("Precio: "))
    Importe_C = (cant_C * precio_C)
    print(f"Importe del producto C: {Importe_C}")
    print("------------------------------------")
    print("") #espacio
    # ---- Primer semestre C ----

    # ---- Segundo semestre C ----
    print("------------------------------------")
    print(" --- 2do semestre del producto C ---")
    cant_C = int(input("Numero de unidades: "))
    precio_C = int(input("Precio: "))
    Importe_C2 = (cant_C * precio_C)
    print(f"Importe del producto C: {Importe_C2}")
    print("------------------------------------")
    print("")#espacio
    # ---- Segundo semestre C ----

    # ---- Total C ----
    print("------------------------------------")
    print("    ---- Total del producto C ----  ")
    Total_C= (Importe_C + Importe_C2)
    print(f"Total del producto B: {Total_C}")
    print("------------------------------------")
    print("") #espacio
    # ---- Total C ----
    # -------- PRODUCTOS --------


    # -------- VENTAS -----------
    print("------------------------------------")
    print("   ---- Ventas por semestre ----    ")
    Total_Semestre = (Importe_A + Importe_B + Importe_C)
    Total_Semestre_2 = (Importe_A2 + Importe_B2 + Importe_C2)
    Total_Anual = (Total_A + Total_B + Total_C)
    print(f"Total primer semestre {Total_Semestre}")
    print(f"Total segundo semestre {Total_Semestre_2}")
    print(f"Total anual {Total_Anual}")
    print("------------------------------------")
    print("") #espacio
    # -------- VENTAS -----------


    # -------- Continue... -----------
    input("Pulse Enter para ingresar en --Saldo clientes-- ...") 
    print("") #espacio
    # -------- Continue... -----------


# -------- Saldo Clientes -------
def SaldoFlujo():
    print("------------------------------------")
    print("   ------ Saldo clientes ------     ")
    print("Saldo de clientes: ")
    saldo_cliente= int(input())
    print(f"Ventas: {Total_Anual}")
    total_clientes= (saldo_cliente + Total_Anual)
    print(f"Saldo total de clientes: {total_clientes}")
    print("------------------------------------")
    print("") #espacio
# -------- Saldo Clientes -------

# -------- Entradas -------
    print("--------------------------------------")
    print("        ------ Entradas ------        ")
    primer_año= int(input("Cobro del primer año: "))
    segundo_año= int(input("Cobro del segundo año: "))
    entradas_total= (primer_año + segundo_año)
    print(f"Total de las entradas: {entradas_total} ")
    total_clientes2= (total_clientes - entradas_total)
    print(f"Total del saldo clientes: {total_clientes2}")
    print("--------------------------------------")
    print("") #espacio
# -------- Entradas -------


# -------- Continue... -----------
    input("Pulse Enter para ingresar en --Presupuesto de la producción-- ...") 
    print("") #espacio
# -------- Continue... -----------


# -------- Presupuesto de producciones --------
def PresupuestoProduccion():
    print("--------------------------------------")
    print("---- Presupuesto de la produccion ----")
    print("--------------------------------------")
    print("")#espacio


    #---- 1er semestre produccion de producto A ----
    print("------------------------------------------------------")
    print("---- 1er semestre, presupuesto de la produccion A ----")
    no_unidades_A = int(input("Numero de unidades: "))
    inventario_finalA = int(input("Inventario final: "))
    total_unidades = (no_unidades_A + inventario_finalA)
    print(f"Total de unidades: {total_unidades}")
    inventario_inicialA = int(input("Inventario incial: "))
    unidades_producir = (total_unidades - inventario_inicialA)
    print(f"Las unidades a producir en el primer semestre: {unidades_producir}")
    print("------------------------------------------------------")
    print("") #espacio
    #---- 1er semestre produccion de producto A ----
    
    #---- 2do semestre produccion de producto A ----
    print("------------------------------------------------------")
    print("---- 2do semestre, presupuesto de la produccion A ----")
    no_unidades_A2 = int(input("Numero de unidades: "))
    inventario_finalA2 = int(input("Inventario final: "))
    total_unidades2 = (no_unidades_A2 + inventario_finalA2)
    print(f"Total de unidades: {total_unidades2}")
    inventario_inicialA2 = int(input("Inventario incial: "))
    unidades_producirA2 = (total_unidades2 - inventario_inicialA2)
    print(f"Las unidades a producir en el segundo semestre: {unidades_producirA2}")
    print("------------------------------------------------------")
    print("") #espacio
    #---- 2do semestre produccion de producto A ----

    #---- Total produccion de producto A ----
    print("----------------------------------------")
    print("---- Total de produccion producto A ----")
    no_unidades_AT = (no_unidades_A + no_unidades_A2)
    print(f"Unidades a vender: {no_unidades_AT}")
    print(f"Inventario final: {inventario_finalA2}")
    Total_UnidadesA= (no_unidades_AT + inventario_finalA2)
    print(f"Total de unidades: {Total_UnidadesA}")
    inventario_inicialA = inventario_finalA
    TotalT= (Total_UnidadesA - inventario_inicialA)
    print(f"Unidades totales de producto A: {TotalT}")
    print("--------------------------------------")
    print("") #espacio
    #---- Total produccion de producto A ----


    #---- 1er semestre produccion de producto B ----
    print("------------------------------------------------------")
    print("---- 1er semestre, presupuesto de la produccion B ----")
    no_unidades_B = int(input("Numero de unidades: "))
    inventario_finalB = int(input("Inventario final: "))
    total_unidades = (no_unidades_B + inventario_finalB)
    print(f"Total de unidades: {total_unidades}")
    inventario_inicialB = int(input("Inventario incial: "))
    unidades_producir = (total_unidades - inventario_inicialB)
    print(f"Las unidades a producir en el primer semestre son: {unidades_producir}")
    print("------------------------------------------------------")
    print("") #espacio
    #---- 1er semestre produccion de producto B ----
    
    #---- 2do semestre produccion de producto B ----
    print("------------------------------------------------------")
    print("---- 2do semestre, presupuesto de la produccion B ----")
    no_unidades_B2 = int(input("Numero de unidades: "))
    inventario_finalB2 = int(input("Inventario final: "))
    total_unidades2 = (no_unidades_B2 + inventario_finalB2)
    print(f"Total de unidades: {total_unidades2}")
    inventario_inicialB2 = int(input("Inventario incial: "))
    unidades_producirB2 = (total_unidades2 - inventario_inicialB2)
    print(f"Las unidades a producir en el segundo semestre son: {unidades_producirB2}")
    print("------------------------------------------------------")
    print("") #espacio
    #---- 2do semestre produccion de producto B ----

    #---- Total produccion de producto B ----
    print("----------------------------------------")
    print("---- Total de produccion producto B ----")
    no_unidades_BT = (no_unidades_B + no_unidades_B2)
    print(f"Unidades a vender: {no_unidades_BT}")
    print(f"Inventario final: {inventario_finalB2}")
    Total_UnidadesB= (no_unidades_BT + inventario_finalB2)
    print(f"Total de unidades: {Total_UnidadesB}")
    inventario_inicialB = inventario_finalB
    TotalBT= (Total_UnidadesB - inventario_inicialB)
    print(f"Unidades totales de producto B: {TotalBT}")
    print("----------------------------------------")
    print("") #espacio
    #---- Total produccion de producto B ----


    #---- 1er semestre produccion de producto C ----
    print("------------------------------------------------------")
    print("---- 1er semestre, presupuesto de la produccion C ----")
    no_unidades_C = int(input("Numero de unidades: "))
    inventario_finalC = int(input("Inventario final: "))
    total_unidades = (no_unidades_C + inventario_finalC)
    print(f"Total de unidades: {total_unidades}")
    inventario_inicialC = int(input("Inventario incial: "))
    unidades_producir = (total_unidades - inventario_inicialC)
    print(f"Las unidades a producir en el primer semestre son: {unidades_producir}")
    print("------------------------------------------------------")
    print("") #espacio
    #---- 1er semestre produccion de producto C ----
    
    #---- 2do semestre produccion de producto C ----
    print("------------------------------------------------------")
    print("---- 2do semestre, presupuesto de la produccion C ----")
    no_unidades_C2 = int(input("Numero de unidades: "))
    inventario_finalC2 = int(input("Inventario final: "))
    total_unidades2 = (no_unidades_C2 + inventario_finalC2)
    print(f"Total de unidades: {total_unidades2}")
    inventario_inicialC2 = int(input("Inventario incial: "))
    unidades_producirC2 = (total_unidades2 - inventario_inicialC2)
    print(f"Las unidades a producir en el segundo semestre son: {unidades_producirC2}")
    print("------------------------------------------------------")
    print("") #espacio
    #---- 2do semestre produccion de producto C ----

    #---- Total produccion de producto C ----
    print("--------------------------------------")
    print("---- Total de produccion producto C ----")
    no_unidades_CT = (no_unidades_C + no_unidades_C2)
    print(f"Unidades a vender: {no_unidades_CT}")
    print(f"Inventario final: {inventario_finalC2}")
    Total_UnidadesC= (no_unidades_CT + inventario_finalC2)
    print(f"Total de unidades: {Total_UnidadesC}")
    inventario_inicialC = inventario_finalC
    TotalCT= (Total_UnidadesC - inventario_inicialC)
    print(f"Unidades totales de producto C: {TotalCT}")
    print("--------------------------------------")
    #---- Total produccion de producto C ----
    print("") #espacio


# -------- Continue... -----------
    input("Pulse Enter para ingresar en --Presupuesto para materiales-- ...") 
    print("") #espacio
# -------- Continue... -----------


# -------- Presupuesto de materiales --------
def PresupuestoReqMateriales():
    print("-------------------------------------------")
    print("------- Presupuesto para materiales -------")
    print("-------------------------------------------")
    print("") #espacio

    # ----- Producto A -----
    print("-------------------------------------------")
    print("  ------- Unidades del producto A -------  ")
    no_unidades_A = int(input("Numero de unidades 1er semestre: "))
    no_unidades_A2 = int(input("Numero de unidades 2do semestre: "))
    print("-------------------------------------------")
    print("") #espacio
    # ----- Producto A -----

    # ----- Producto B -----
    print("-------------------------------------------")
    print("  ------- Unidades del producto B -------  ")
    no_unidades_B = int(input("Numero de unidades 1er semestre: "))
    no_unidades_B2 = int(input("Numero de unidades 2do semestre: "))
    print("-------------------------------------------")
    print("") #espacio
    # ----- Producto B -----

    # ----- Producto C -----
    print("-------------------------------------------")
    print("  ------- Unidades del producto C -------  ")
    no_unidades_C = int(input("Numero de unidades 1er semestre: "))
    no_unidades_C2 = int(input("Numero de unidades 2do semestre: "))
    print("-------------------------------------------")
    print("") #espacio
    # ----- Producto C -----


    # ----- Material A -----
    print("-------------------------------------------")
    print("  ----- Requerimientos de material A ----  ")
    req_A = float(input("Requermientos del 1er semestre: "))
    req_A2 = float(input("Requermientos del 2do semestre: "))
    print("-------------------------------------------")
    print("") #espacio
    # ----- Material A -----


    # ----- Material B -----
    print("-------------------------------------------")
    print("  ----- Requerimientos de material B ----  ")
    req_B = float(input("Requermientos del 1er semestre: "))
    req_B2 = float(input("Requermientos del 2do semestre: "))
    print("-------------------------------------------")
    print("") #espacio
    # ----- Material B -----


    # ----- Material C -----
    print("-------------------------------------------")
    print("  ----- Requerimientos de material C ----  ")
    req_C = float(input("Requermientos del 1er semestre: "))
    req_C2 = float(input("Requermientos del 2do semestre: "))
    print("-------------------------------------------")
    print("")#espacio
    # ----- Material C -----

    total_A1 = (no_unidades_A * req_A)  #MATERIAL A
    total_A2 = (no_unidades_A2 * req_A2)
    total_AT = (total_A1 + total_A2)

    total_B1 = (no_unidades_B * req_B)  #MATERIAL B
    total_B2 = (no_unidades_B2 * req_B2)
    total_BT = (total_B1 + total_B2)

    total_C1 = (no_unidades_C * req_C)   #MATERIAL C
    total_C2 = (no_unidades_C2 * req_C2)
    total_CT = (total_C1 + total_C2)

    print("-------------------------------------------")
    print("---- Total requerimientos de material A ---")
    print(f"Total 1er semestre: {total_A1}")
    print(f"Total 2do semestre: {total_A2}")
    print(f"Total de requerimientos: {total_AT}")
    print("-------------------------------------------")
    print("")#espacio

    print("-------------------------------------------")
    print("---- Total requerimientos de material B ---")
    print(f"Total 1er semestre: {total_B1}")
    print(f"Total 2do semestre: {total_B2}")
    print(f"Total de requerimientos: {total_BT}")
    print("-------------------------------------------")
    print("")#espacio

    # ----- Producto C -----
    print("-------------------------------------------")
    print("---- Total requerimientos de material C ---")
    print(f"Total 1er semestre: {total_C1}")
    print(f"Total 2do semestre: {total_C2}")
    print(f"Total de requerimientos: {total_CT}")
    print("-------------------------------------------")
    print("")#espacio
    # ----- Producto C -----

# -------- Presupuesto de materiales --------


# -------- Continue... -----------
    input("Pulse cualquier letra del teclado para ingresar en --Presupuesto para compra de materiales-- ...") 
    print("") #espacio
# -------- Continue... -----------


# -------- Presupuesto para compra de materiales ------------
def PresupuestoCompraMateriales():
    print("-------------------------------------")
    print("Presupuesto para compra de materiales")
    print("-------------------------------------")
    print("")#espacio

    # ----- Material A ------
    # ----- Primer semestre A -----
    print("-------------------------------------")
    print(" ----------- Material A ------------ ")
    print("---------- 1er semestre -------------")
    req_A = int(input("Requerimento de materiales: "))
    inv_finalA = int(input("Inventario final: "))
    total_materialesA = (req_A + inv_finalA)
    print(f"Materiales: {total_materialesA} ")
    inventario_inicialA = int(input("Inventario incial: "))
    total_materialesA_t = (total_materialesA - inventario_inicialA)
    print(f"Material a comprar: {total_materialesA_t}")
    precio_compraA = int(input("Precio compra: ")) ############################## A
    TotalMatA = (total_materialesA_t * precio_compraA) ########################## A 
    print(f"Total Material A en 1er semestre: {TotalMatA}")
    print("-------------------------------------")
    print("")#espacio
    # ----- Primer semestre A -----


    # ----- Segundo semestre A -----
    print("-------------------------------------")
    print(" ----------- Material A ------------ ")
    print("---------- 2do semestre -------------")
    req_A2 = int(input("Requerimento de materiales: "))
    inv_finalA2 = int(input("Inventario final: "))
    total_materialesA = (req_A + inv_finalA)
    print(f"Total de Materiales: {total_materialesA} ")
    inventario_inicialA2 = int(input("Inventario incial: "))
    total_materialesA_t2 = (total_materialesA - inventario_inicialA2)
    print(f"Total de material a comprar: {total_materialesA_t2}")
    precio_compraA2 = int(input("Precio compra: ")) ############################### A2
    TotalMatA2 = (total_materialesA_t2 * precio_compraA2) ########################## A2
    print(f"Total Material A en 2do semestre: {TotalMatA2}")
    print("-------------------------------------")
    print("")#espacio
    # ----- Segundo semestre A -----

    # ----- Total A -----
    print("-------------------------------------")
    print(" ----------- Material A ------------ ")
    print("--------- Total materiales ----------")
    print(f"Requerimentos materiales: {req_A + req_A2}")
    print(f"Inventario final: {inv_finalA + inv_finalA2}")
    print(f"Materiales: {total_materialesA + total_materialesA_t2}")
    print(f"Inventario inicial: {inventario_inicialA + inventario_inicialA2}")
    print(f"Materiales a comprar: {total_materialesA_t + total_materialesA_t2}")
    print(f"Material: ${TotalMatA + TotalMatA2} ")
    print("")#espacio
    # ----- Total A -----

#######################################################################################
    # ----- Material B ------
    # ----- Primer semestre B -----
    print("-------------------------------------")
    print(" ----------- Material B ------------ ")
    print("---------- 1er semestre -------------")
    req_B = int(input("Requerimento de materiales: "))
    inv_finalB = int(input("Inventario final: "))
    total_materialesB = (req_B + inv_finalB)
    print(f"Materiales: {total_materialesB} ")
    inventario_inicialB = int(input("Inventario incial: "))
    total_materialesB_t = (total_materialesB - inventario_inicialB)
    print(f"Material a comprar: {total_materialesB_t}")
    precio_compraB = int(input("Precio de compra: ")) ############################# B
    TotalMatB = (total_materialesB_t * precio_compraB) ############################ B
    print(f"Total Material B: {TotalMatB}")
    print("-------------------------------------")
    print("")#espacio

    # ----- Segundo semestre B -----
    print("-------------------------------------")
    print(" ----------- Material B ------------ ")
    print("---------- 2do semestre -------------")
    req_B2 = int(input("Requerimento de materiales: "))
    inv_finalB2 = int(input("Inventario final: "))
    total_materialesB = (req_B + inv_finalB)
    print(f"Total de Materiales: {total_materialesB} ")
    inventario_inicialB2 = int(input("Inventario incial: "))
    total_materialesB_t2 = (total_materialesB - inventario_inicialB2)
    print(f"Total de material a comprar: {total_materialesB_t2}")
    precio_compraB2 = int(input("Precio de compra: ")) ############################# B2
    TotalMatB2 = (total_materialesB_t * precio_compraB2) ########################### B2
    print(f"Total Material B Segundo Semestre: {TotalMatB2}")
    print("-------------------------------------")
    print("")#espacio
    # ----- Segundo semestre B -----

    # ----- Total B -----
    print("-------------------------------------")
    print(" ----------- Material B ------------ ")
    print("--------- Total materiales ----------")
    print(f"Requerimentos materiales: {req_B + req_B2}")
    print(f"Inventario final: {inv_finalB + inv_finalB2}")
    print(f"Materiales: {total_materialesB + total_materialesB_t2}")
    print(f"Inventario inicial: {inventario_inicialB + inventario_inicialB2}")
    print(f"Materiales a comprar: {total_materialesB_t + total_materialesB_t2}")
    print(f"Material: ${TotalMatB + TotalMatB2} ")
    print("-------------------------------------")
    print("")#espacio
    # ----- Total A -----

    # ----- Primer semestre C -----
    print("-------------------------------------")
    print(" ----------- Material C ------------ ")
    print("---------- 1er semestre -------------")
    req_C = int(input("Requerimento de materiales: "))
    inv_finalC = int(input("Inventario final: "))
    total_materialesC = (req_C + inv_finalC)
    print(f"Materiales: {total_materialesC} ")
    inventario_inicialC = int(input("Inventario incial: "))
    total_materialesC_t = (total_materialesC - inventario_inicialC)
    print(f"Material a comprar: {total_materialesC_t}")
    precio_compraC = int(input("Precio de compra: ")) ############################ C
    TotalMatC = (total_materialesC_t * precio_compraC) ########################### C
    print(f"Total Material C: {TotalMatC}")
    print("-------------------------------------")
    print("")#espacio
    # ----- Primer semestre C -----

    # ----- Segundo semestre C -----
    print("-------------------------------------")
    print(" ----------- Material C ------------ ")
    print("---------- 2do semestre -------------")
    req_C2 = int(input("Requerimento de materiales: "))
    inv_finalC2 = int(input("Inventario final: "))
    total_materialesC = (req_C + inv_finalC)
    print(f"Total de Materiales: {total_materialesC} ")
    inventario_inicialC2 = int(input("Inventario incial: "))
    total_materialesC_t2 = (total_materialesC - inventario_inicialC2)
    print(f"Total de material a comprar: {total_materialesC_t2}")
    precio_compraC2 = int(input("Precio de compra: ")) ############################### C2
    TotalMatC2 = (total_materialesC_t * precio_compraC2) ############################# C2
    print(f"Total Material C Segundo Semestre: {TotalMatC2}")
    print("-------------------------------------")
    print("")#espacio
    # ----- Segundo semestre C -----

    # ----- Total C -----
    print("-------------------------------------")
    print(" ----------- Material C ------------ ")
    print("--------- Total materiales ----------")
    print(f"Requerimentos de Materiales: {req_C + req_C2}")
    print(f"Inventario Final: {inv_finalC + inv_finalC2}")
    print(f"Materiales: {total_materialesC + total_materialesC_t2}")
    print(f"Inventario Inicial: {inventario_inicialC + inventario_inicialC2}")
    print(f"Materiales a comprar: {total_materialesC_t + total_materialesC_t2}")
    print(f"Material: ${TotalMatC + TotalMatC2} ")
    print("-------------------------------------")
    print("")#espacio
    # ----- Total C -----
#######################################################################################


# -------- Continue... -----------
    input("Pulse Enter para ingresar en --Saldo provedores y flujos de salida-- ...") 
    print("") #espacio
# -------- Continue... -----------


def SaldoProvFlujo():
    print("---------------------------------------")
    print("--Saldo provedores y flujos de salida--")
    saldo_c = int(input("Saldo clientes: "))
    total_clientes = (saldo_c + Total_Anual)
    print(f"Saldo total clientes: {total_clientes}")
    print("Entradas efectivo")
    Año_1 = int(input("Cobranza 1er año: "))
    Año_2 = int(input("Cobranza 2do año: "))
    total_entradas = (Año_1 + Año_2)
    print(f"Total entradas: {total_entradas}")
    Total_Clientes2 = (total_clientes - total_entradas)
    print(f"Saldo clientes: {Total_Clientes2}")
    print("---------------------------------------")
    print("")#espacio

# -------- Continue... -----------
    input("Pulse Enter para ingresar en --Presupuesto mano directa de obra-- ...") 
    print("") #espacio
# -------- Continue... -----------

def manoObraDirecta():
    global total_horas_reqSum
    print("------------------------------------------")
    print("---- Presupuesto mano directa de obra ----")
    print("------------------------------------------")
    print("")#espacio

    # ---- Producto A PRIMER SEMESTRE -----
    print("---------------------------------")
    print("---- 1er semestre producto A ----")
    unidades_p1= int(input("Unidades a producir: "))
    horas_por_unidad= int(input("Horas requeridas por unidad: "))
    total_horas_req1 = (unidades_p1 * horas_por_unidad)
    print(f"Total de horas requeridas: {total_horas_req1}")
    cuota_por_hora= int(input("Cuota por hora: "))
    importe_mano_obra_directa = total_horas_req1 * cuota_por_hora
    print(f"El importe de MOD: {importe_mano_obra_directa}")
    print("")#espacio
    # ---- Producto A PRIMER SEMESTRE -----

    # ---- Producto A SEGUNDO SEMESTRE -----
    print("---------------------------------")
    print("---- 2do semestre producto A ----")
    unidades_p2 = int(input("Unidades a producir: "))
    horas_por_unidad2 = int(input("Horas requeridas por unidad: "))
    total_horas_req2 = (unidades_p2 * horas_por_unidad2)
    print(f"Total de horas requeridas: {total_horas_req2}")
    cuota_por_hora2 = int(input("Cuota por hora: "))
    importe_mano_obra_directa2 = total_horas_req2 * cuota_por_hora2
    print("El importe de MOD: ", importe_mano_obra_directa2)
    print("---------------------------------")
    print("")#espacio
    # ---- Producto A SEGUNDO SEMESTRE -----

    # ---- Producto A TOTAL -----
    print("---------------------------------")
    print("------ Total de producto A ------")
    unidades_totales = (unidades_p1 + unidades_p2)
    print(f"Total de unidades a producir: {unidades_totales}")
    Total_horas_unidad = (horas_por_unidad + horas_por_unidad2)
    print(f"Total de horas requeridas por unidad: {Total_horas_unidad}")
    Total_horas_req = (unidades_totales * Total_horas_unidad)
    print(f"Total de horas requeridas: {Total_horas_req}")
    Total_importemano_obra_directa = (importe_mano_obra_directa + importe_mano_obra_directa2)
    print(f"Total del importe de MOD: {Total_importemano_obra_directa}")
    print("---------------------------------")
    print("")#espacio
    # ---- Producto A TOTAL -----
    
    # ---- Producto B PRIMER SEMESTRE -----
    print("---------------------------------")
    print("---- 1er semestre producto B ----")
    unidades_p1B = int(input("Unidades a producir: "))
    horas_por_unidadB1 = int(input("Horas requeridas por unidad: "))
    total_horas_reqB1 = (unidades_p1B * horas_por_unidadB1)
    print(f"Total de horas requeridas: {total_horas_reqB1}")
    cuota_por_horaB1= int(input("Cuota por hora: "))
    importe_mano_obra_directaB1= total_horas_reqB1 * cuota_por_horaB1
    print(f"El importe de MOD: {importe_mano_obra_directaB1}")
    print("---------------------------------")
    print("")#espacio
    # ---- Producto B PRIMER SEMESTRE -----

    # ---- Producto B SEGUNDO SEMESTRE -----
    print("---------------------------------")
    print("---- 2do semestre producto B ----")
    unidades_p1B2 = int(input("Unidades a producir: "))
    horas_por_unidadB2 = int(input("Horas requeridas por unidad: "))
    total_horas_reqB2 = (unidades_p1B2 * horas_por_unidadB2)
    print(f"Total de horas requeridas: {horas_por_unidadB1 + total_horas_reqB2}")
    cuota_por_horaB2 = int(input("Cuota por hora: "))
    importe_mano_obra_directaB2 = total_horas_reqB2 * cuota_por_horaB2
    print(f"El importe de MOD: {importe_mano_obra_directaB2}")
    print("---------------------------------")
    print("")#espacio
    # ---- Producto B SEGUNDO SEMESTRE -----

    #----- Producto B total -----
    print("---------------------------------")
    print("------ Total de producto B ------") 
    unidades_totalesB = (unidades_p1B + unidades_p1B2)
    print(f"El total de unidades a producir es de: {unidades_totalesB}")
    uniTotal_horas_unidadB = (horas_por_unidadB1)
    print(f"El total de horas requeridas por unidad es de: {uniTotal_horas_unidadB}")
    Total_horas_reqB = (unidades_totalesB * uniTotal_horas_unidadB)
    print("El total de horas requeridas es de: ", Total_horas_reqB)
    Total_importemano_obra_directaB = (importe_mano_obra_directaB1 + importe_mano_obra_directaB2)
    print("El total del importe de MOD: ", Total_importemano_obra_directaB)
    print("---------------------------------")
    print("")#espacio
    #----- Producto B total -----

    #----- Total presupuesto -----
    print("---------------------------------")
    print("------- Total presupuesto -------")
    print(f"Unidades a producir: {unidades_totales + unidades_totalesB} ")
    print(f"Horas requeridas por unidad: {Total_horas_req + Total_horas_reqB}")
    total_horas_reqSum = Total_horas_req + total_horas_reqB1
    print(f"Horas requeridas: {Total_horas_req + total_horas_reqB1}")
    print(f"Importe MOD: {Total_importemano_obra_directa + Total_importemano_obra_directaB}")
    print("---------------------------------")
    print("")#espacio
    #----- Total presupuesto -----

    #----- Horas requeridas -----
    print("---------------------------------")
    print("------- Horas requeridas --------")
    print(f"1er semestre: {total_horas_req1 + total_horas_reqB1}")
    print(f"2do semestre: {total_horas_req2 + total_horas_reqB2}")
    print(f"Total anual: {Total_horas_req + Total_horas_reqB}")
    print("---------------------------------")
    print("")#espacio
    #----- Horas requeridas -----

    #----- Total del MOD -----
    print("---------------------------------")
    print("--------- Total del MOD ---------")
    print(f"El total de MOD por el 1er semestre: {importe_mano_obra_directa + importe_mano_obra_directaB1}")
    print(f"El total de MOD por el 2do semestre: {importe_mano_obra_directa2 + importe_mano_obra_directaB2} ")
    print(f"El total de MOD por semestre: {Total_importemano_obra_directa + Total_importemano_obra_directaB}")
    print("---------------------------------")
    print("")#espacio
    #----- Total del MOD -----


# -------- Continue... -----------
    input("Pulse Enter para ingresar en --Gastos indirectos de fabricacion-- ...") 
    print("") #espacio
# -------- Continue... -----------


# ----- Gastos indirectos de fabricacion -----
def gastosIndirectosFabricacion():
    global total_GIF
    print("------------------------------------------")
    print("---- Gastos indirectos de fabricación ----")
    print("------------------------------------------")
    print("")#espacio

    print("------------------------------------------")
    print("    ------ 1er semestre de GIF -------    ")
    seguros_s1 = int(input("Seguros: "))
    depreciacion_s1 = int(input("Depreciaciones: "))
    energeticos_s1 = int(input("Energeticos: "))
    mantenimiento_s1 = int(input("Mantenimientos: "))
    varios_s1 = int(input("Varios: "))
    totalGIF_s1 = (depreciacion_s1 + seguros_s1 + mantenimiento_s1 + energeticos_s1 + varios_s1)
    print(f"Total del GIF 1er semestre: {totalGIF_s1}")
    print("------------------------------------------")
    print("")#espacio

    print("------------------------------------------")
    print("    ------ 2do semestre de GIF -------    ")
    seguros_s2= int(input("Seguros: "))
    depreciacion_s2= int(input("Depreciaciones: "))
    energeticos_s2= int(input("Energeticos: "))
    mantenimiento_s2= int(input("Mantenimientos: "))
    varios_s2= int(input("Varios: "))
    totalGIF_s2= (depreciacion_s2 + seguros_s2 + mantenimiento_s2 + energeticos_s2 + varios_s2)
    print(f"Total del GIF 2do semestre: {totalGIF_s2}")
    print("------------------------------------------")
    print("")#espacio
    
    total_depreciacion = (depreciacion_s1 + depreciacion_s2)
    print(f"Total depreciación: {total_depreciacion}")
    print("")#espacio
    
    total_seguros = (seguros_s1 + seguros_s2)
    print(f"Total Seguros: {total_seguros}")
    print("")#espacio
    
    total_mantenimiento = (mantenimiento_s1 + mantenimiento_s2)
    print(f"Total mantenimiento: {total_mantenimiento}")
    print("")#espacio

    total_energeticos = (energeticos_s1 + energeticos_s2)
    print(f"Total energeticos: {total_energeticos}")
    print("")#espacio
    
    total_varios = (varios_s1 + varios_s2)
    print(f"Total varios: {total_varios}")
    print("")#espacio


 # -------- Continue... -----------
    input("Pulse Enter para ingresar en --Los gastos / Costos Indirectos de Fabricación (GIF)-- ...") 
    print("") #espacio
# -------- Continue... -----------


    print("---------------------------------------------------")
    print("Los gastos / Costos Indirectos de Fabricación (GIF)")
    total_GIF = (total_depreciacion + total_seguros + total_mantenimiento + total_energeticos + total_varios)
    print(f"Total de GIF: {total_GIF}")
    print(f"El total de horas MOD anual: {total_horas_reqSum}")
    total_GIF = (total_GIF / total_horas_reqSum)
    print(f"El costo por hora de GIF: {total_GIF}")
    print("---------------------------------------------------")
    print("")#espacio


# -------- Continue... -----------
    input("Pulse enter para ingresar en --Gastos de operacion-- ...") 
    print("") #espacio
# -------- Continue... -----------


# ----- Gastos de operacion -----
def PresupuestoGastosOp():
    print("-----------------------------")
    print("---- Gastos de operación ----")
    print("-----------------------------")
    print("")#espacio

    # ---- GO Primer Semestre ----
    print("----------------------")
    print("---- 1er semestre ----")
    depreciacion_s1 = int(input("Depreciación: "))
    salarios_s1 = int(input("Salarios: "))
    comisiones_s1 = int(input("Comisiones: "))
    varios_s1 = int(input("Varios: "))
    intereses_s1 = int(input("Intereses por prestamo: "))
    print(f"Total: {depreciacion_s1 + salarios_s1 + comisiones_s1 + varios_s1 + intereses_s1}")
    print("----------------------")
    print("")#espacio
    # ---- GO Primer Semestre ----

    # ---- GO Segundo Semestre ----
    print("----------------------")
    print("---- 2do semestre ----")
    depreciacion_s2 = int(input("Depreciación: "))
    salarios_s2 = int(input("Salarios: "))
    comisiones_s2 = int(input("Comisiones: "))
    varios_s2 = int(input("Varios: "))
    intereses_s2 = int(input("Intereses por prestamo: "))
    print(f"Total: {depreciacion_s2 + salarios_s2 + comisiones_s2 + varios_s2 + intereses_s2}")
    print("----------------------")
    print("")#espacio
    # ---- GO Segundo Semestre ----

    # ---- GO TOTAL ----
    print("----------------------")
    print("---- Total de GO -----")
    print(f"Total depreciación: {depreciacion_s1 + depreciacion_s2}")
    print(f"Sueldos y salarios: {salarios_s1 + salarios_s2}")
    print(f"Comisiones: {comisiones_s1 + comisiones_s2}")
    print(f"Varios: {varios_s1 + varios_s2}")
    print(f"Intereses por préstamo: {intereses_s1 + intereses_s2}")
    print(f"Total de gastos de operación: {depreciacion_s1+ salarios_s1 +comisiones_s1+ varios_s1 + intereses_s1 + depreciacion_s2 + salarios_s2 + comisiones_s2 + varios_s2 + intereses_s2}")
    print("----------------------")
    print("")#espacio
    # ---- GO TOTAL ----
    
# -------- Continue... -----------
    input("Pulse Enter para ingresar en --Costo unitario producto terminado-- ...") 
    print("") #espacio
# -------- Continue... -----------

def costoUnitario():
    print("-------------------------------------------")
    print("---- Costo unitario producto terminado ----")
    print("-------------------------------------------")
    print("")#espacio
    
    # ---- Producto A ----
    print("--------------------")
    print("---- Producto A ----")
    costo_a = int(input("Costo: "))
    cantidad_a = int(input("Cantidad: "))
    costo_unitario = costo_a * cantidad_a 
    print(f"Costo unitario: {costo_unitario}")
    print("--------------------")
    print("")#espacio
    # ---- Producto A ----

    # ---- Producto B ----
    print("--------------------")
    print("---- Producto B ----")
    costo_b = int(input("Costo: "))
    cantidad_b = int(input("Cantidad: "))
    costo_unitario_b = costo_b * cantidad_b 
    print(f"Costo unitario: {costo_unitario_b}")
    print("--------------------")
    print("")#espacio

    # ---- Producto C ----
    print("--------------------")
    print("---- Producto C ----")
    costo_c = int(input("Costo: "))
    cantidad_c = int(input("Cantidad: "))
    costo_unitario_c = costo_c * cantidad_c 
    print(f"Costo unitario: {costo_unitario_c}",)
    print("--------------------")
    print("")#espacio
    # ---- Producto C ----

    # ---- Mano de obra ----
    print("--------------------")
    print("--- Mano de obra ---")
    costo_mano = int(input("Costo: "))
    cant_mano = int(input("Cantidad: "))
    costo_unitario_mano = costo_mano * cant_mano 
    print(f"Costo unitario: {costo_unitario_mano}")
    print("--------------------")
    print("")#espacio
    # ---- Mano de obra ----

    # ---- Gastos indirectos fabricacion ----
    print("---------------------------------------")
    print("---- Gastos indirectos fabricacion ----")
    costo_gastos_fab = int(input("Costo: "))
    print("Cantidad: ")
    cant_gastos = int(input())
    costo_unitario_fab = costo_gastos_fab * cant_gastos 
    print(f"Costo unitario: {costo_unitario_fab}")
    print(f"Costo unitario total: ${costo_unitario+costo_unitario_b+costo_unitario_c+costo_unitario_mano+costo_unitario_fab}")
    print("---------------------------------------")
    print("")#espacio
    # ---- Gastos indirectos fabricacion ----

# -------- Continue... -----------
    input("Pulse Enter para ingresar en -- Inventarios finales -- ...") 
    print("") #espacio
# -------- Continue... -----------

def InventariosFinales():
    print("-----------------------------")
    print("---- Inventarios finales ----")
    print("-----------------------------")
    print("")#espacio

    print("----------------------------------------")
    print("---- Inventario Final de Materiales ----")
    print("------------- Material A ---------------")
    unidades_a = int(input("Unidades: "))
    costo_a = int(input("Costo unitario: "))
    costo_total_a = (unidades_a * costo_a)
    print(f"Costo total: {costo_total_a}")
    print("----------------------------------------")
    print("")#espacio

    print("----------------------------------------")
    print("---- Inventario Final de Materiales ----")
    print("------------- Material B ---------------")
    unidades_b = int(input("Unidades: "))
    costo_b = float(input("Costo unitario: "))
    costo_total_b = (unidades_b * costo_b)
    print(f"Costo total: {costo_total_b}")
    print("----------------------------------------")
    print("")#espacio

    print("----------------------------------------")
    print("---- Inventario Final de Materiales ----")
    print("------------- Material C ---------------")
    unidades_c = int(input("Unidades: "))
    costo_c = int(input("Costo Unitario: "))
    costo_c = (unidades_c * costo_c)
    print(f"El costo total es de: {costo_c}")
    print("----------------------------------------")
    print("")#espacio

    inventario_final_mat = (costo_total_a + costo_total_b + costo_c)
    print("----------------------------------------")
    print(f"Inventario final material: {inventario_final_mat}")
    print("----------------------------------------")
    print("")#espacio

    print("---------------------------------------------")
    print("---- Inventario final producto terminado ----")
    print("Producto CL")
    print("Unidades: ")
    UDSA2= int(input())
    print("Costo unitario: ")
    CUA2= float(input())
    CTA2= (UDSA2 * CUA2)
    print("El costo total: ", CTA2)
    print("---------------------------------------------")
    print("")#espacio

    print("---------------------")
    print("---- Producto CE ----")
    print("Unidades: ")
    UDSB2= int(input())
    print("Costo unitario: ")
    CUB2= float(input())
    CTB2= (UDSB2 * CUB2)
    print("El costo total: ", CTB2)
    print("---------------------")
    print("")#espacio

    print("Producto CR")
    print("Unidades: ")
    UDSC2= int(input())
    print("Costo unitario: ")
    CUC2= float(input())
    CTC2= (UDSC2 * CUC2)
    print("El costo total: ", CTC2)
    print("")#espacio

    inventario_final_mat2= (CTA2 + CTB2 + CTC2)
    print("-------------------------------------------")
    print("El inventario final de producto terminado: ", inventario_final_mat2)
    print("-------------------------------------------")
    print("")#espacio


# -------- Continue... -----------
    input("Pulse Enter para ingresar en -- Estado de costos producción y venta -- ...") 
    print("") #espacio
# -------- Continue... -----------


def EstadoCostoProduccionVenta():
    print("---------------------------------------------")
    print("---- Estado de costos producción y venta ----")
    saldo_inicial = int(input("Saldo inicial materiales: "))
    compras_materiales = int(input("Compras de materiales: "))
    material_disponible = compras_materiales + saldo_inicial
    print(f"Material disponible: {material_disponible}")
    print("---------------------------------------------")
    print("")#espacio

    print("---------------------------------------------")
    print("---- Iventario final de materiales ----")
    inventario_final_m = int(input("Inventario final: "))
    materiales_utilizados = material_disponible - inventario_final_m
    print(f"Materiales utilizados: {materiales_utilizados}")
    mano_obra_directa = int(input("Mano de obra directa: "))
    gastos_fab_indirectos = int(input("Gastos fabricación indirectos: "))
    print(f"Costo de producción: {materiales_utilizados + mano_obra_directa + gastos_fab_indirectos}")
    inventario_inicial = int(input("Inventario inicial productos terminados: "))
    total_productos = materiales_utilizados + mano_obra_directa + gastos_fab_indirectos + inventario_inicial
    print(f"Total producción disponible: {total_productos}")
    inventario_final = int(input(f"Inventario final productos terminados: "))
    print(f"Costo ventas: {total_productos-inventario_final}")
    print("---------------------------------------------")
    print("")#espacio
    
# -------- Continue... -----------
    input("Pulse Enter para ingresar en -- Estado de resultados -- ...") 
    print("") #espacio
# -------- Continue... -----------

def EstadoResultados():
    print("------------------------------")
    print("---- Estado de resultados ----")
    VER1 = int(input("Ventas: " ))
    CDV1 = int(input("Costo de ventas: "))
    UtilidadBruta = VER1-CDV1
    print(f"Utilidad total bruta: {UtilidadBruta}")
    GastosO = int(input("Gastos operacion: "))
    UtilidadO= (UtilidadBruta-GastosO)
    print (f"Total utilidad de operacion: {UtilidadO}")
    ISR1 = int(input("ISR: "))
    PTcant_A = int(input("PTU: "))
    UtilidadN = (UtilidadO-ISR1-PTcant_A)
    print (f"Utilidad neta: {UtilidadN}")
    print("------------------------------")
    print("")#espacio
    
# -------- Continue... -----------
    input("Pulse cualquier letra del teclado para ingresar en -- Estado de flujo efectivo -- ...") 
    print("") #espacio
# -------- Continue... -----------

def EstadoFlujoEfectivo():
    print("----------------------------------")
    print("---- Estado de flujo efectivo ----")
    print("----------------------------------")
    print("")#espacio

    print("-----------------")
    print("--- Entradas ----")
    cobranza_1 = int(input("Cobranza No.1: "))
    cobranza_2 = int(input("Cobranza No.2: "))
    print(f"Total entradas: {cobranza_1 + cobranza_2}")
    print("-----------------")
    print("")#espacio

    print("-----------------")
    print('---- Salidas ----')
    proveedor_1 = int(input("Proveedores No.1: "))
    proveedor_2 = int(input("Proveedores No.2: "))
    Pmano_obra_directa= int(input("Pago mano de obra directa: "))
    gastos_in = int(input("Gastos indirectos de fabricación: "))
    gastos_op = int(input("Gastos de operación: "))
    compra_a = int(input("Maquinarias: "))
    ISR1 = int(input("Pago ISR No.1: "))
    ISR2 = int(input("Pago ISR No.2: "))
    print(f"Total salidas: {proveedor_1 + proveedor_2 + Pmano_obra_directa + gastos_in + gastos_op + compra_a + ISR1 + ISR2}")
    print("-----------------")
    print("")#espacio

# -------- Continue... -----------
    input("Pulse Enter para ingresar en -- Balance general -- ...") 
    print("") #espacio
# -------- Continue... -----------

def BalanceGeneral():
    print("------------------------")
    print("---- Balance general----")
    print("------------------------")
    print("")#espacio

    print("-------------------------")
    print("---Activos circulantes---")
    efectivo_a = int(input("Efectivo: "))
    clientes = int(input("Clientes: "))
    deudores = int(input("Deudores diversos: "))
    empleados = int(input("Empleados: "))
    inventario_m = int(input("Inventario materiales: "))
    inventario_producto = int(input("Inventario producto terminado: "))
    activo_circulante = efectivo_a + clientes + deudores + empleados + inventario_m + inventario_producto
    print(f"Total activos circulantes: $ {activo_circulante}")
    print("-------------------------")
    print("")#espacio

    print("--------------------------------")
    print("---- Activos no circulantes ----")
    terreno = int(input("Terreno: "))
    equipo = int(input("Planta y equipo: "))
    depreciacion = int(input("Depreciación: "))
    activo_no_circulante = terreno + equipo + depreciacion
    print(f"Total activos no circulantes: ${activo_no_circulante}")
    print(f"Total activos: {activo_circulante + activo_no_circulante}")
    print("--------------------------------")
    print("")#espacio

    print("------------------------------")
    print("---- Pasivo a corto plazo ----")
    proveedores = int(input("Proveedores: "))
    documentos = int(input("Documentos pagar: "))
    ISR = int(input("ISR pagar: "))
    PTU = int(input("PTU pagar: "))
    pasivo_corto_plazo = proveedores + documentos + ISR + PTU
    print(f"Total de pasivo corto plazo:$ {pasivo_corto_plazo}")
    print("------------------------------")
    print("")#espacio

    print("------------------------")
    print("---Pasivo largo plazo---")
    prestamos_bancarios = int(input("Préstamos bancarios: "))
    print(f"Total de pasivo largo plazo:$ {prestamos_bancarios}")
    pasivo_total = pasivo_corto_plazo + prestamos_bancarios
    print(f"Pasivo total: {pasivo_total}")
    print("------------------------")
    print("")#espacio
    
    print("--------------------------")
    print("---- Capital contable ----")
    cap_aportado = int(input("Capital aportado: "))
    cap_ganado = int(input("Capital ganado: "))
    utilidad = int(input("Utilidad ejercida: "))
    total_capital = cap_aportado + cap_ganado + utilidad
    print(f"Total capital contable: ${total_capital}")
    print("--------------------------")
    print("")#espacio

    print("--------------------------")
    print("---- Pasivo y capital ----")
    print(total_capital + pasivo_total)
    print("--------------------------")
    print("")#espacio

def main():
    print(f"Presupuesto maestro")
    productosABC()
    SaldoFlujo()
    PresupuestoProduccion()
    PresupuestoReqMateriales()
    PresupuestoCompraMateriales()
    SaldoProvFlujo()
    manoObraDirecta()
    gastosIndirectosFabricacion()
    PresupuestoGastosOp()
    costoUnitario()
    InventariosFinales()
    EstadoCostoProduccionVenta()
    EstadoResultados()
    EstadoFlujoEfectivo()
    BalanceGeneral()

main()